version: "3.9"
services:
  web:
    build: ../NGStore/dist
    ports:
      - "80:80"
    depends_on:
      - datanode
  datanode:
    build: ../NGNode
    ports:
      - "4000:4000"
    volumes:
      - /Users/linsong/Downloads/ngDocker/voldata/:/fruitdata
